#!/bin/bash
# gen-version.sh - Generate version header from git tags
# This makes git the single source of truth for versions

set -e

OUTPUT_FILE="${1:-include/version_generated.h}"
HEADER_GUARD="VERSION_GENERATED_H"

# Get version from git tags
if git describe --tags --always --dirty 2>/dev/null; then
    VERSION=$(git describe --tags --always --dirty 2>/dev/null)
    
    # Parse version tag (e.g., v1.3.0 or v1.3.0-5-g1234567)
    if [[ "$VERSION" =~ ^v?([0-9]+)\.([0-9]+)\.([0-9]+)(-.*)?$ ]]; then
        MAJOR="${BASH_REMATCH[1]}"
        MINOR="${BASH_REMATCH[2]}"
        PATCH="${BASH_REMATCH[3]}"
        EXTRA="${BASH_REMATCH[4]}"
    else
        # No tags, use development version
        MAJOR="0"
        MINOR="0"
        PATCH="0"
        EXTRA="-dev-$VERSION"
    fi
else
    # Not a git repo or no git
    MAJOR="1"
    MINOR="3"
    PATCH="0"
    EXTRA=""
    VERSION="1.3.0"
fi

# Get git commit hash and date
if git rev-parse HEAD >/dev/null 2>&1; then
    GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    GIT_DATE=$(git log -1 --format=%cd --date=short 2>/dev/null || date +%Y-%m-%d)
    GIT_DIRTY=$(git diff --quiet 2>/dev/null || echo "-dirty")
else
    GIT_HASH="unknown"
    GIT_DATE=$(date +%Y-%m-%d)
    GIT_DIRTY=""
fi

# Generate header file
cat > "$OUTPUT_FILE" << HEADER
/*
 * version_generated.h - Auto-generated version information
 * DO NOT EDIT - Generated by scripts/gen-version.sh
 * 
 * Version extracted from git tags at build time.
 * Git is the single source of truth for version numbers.
 */

#ifndef ${HEADER_GUARD}
#define ${HEADER_GUARD}

/* Version from git tag */
#define REFLECTOR_VERSION_MAJOR ${MAJOR}
#define REFLECTOR_VERSION_MINOR ${MINOR}
#define REFLECTOR_VERSION_PATCH ${PATCH}
#define REFLECTOR_VERSION_EXTRA "${EXTRA}${GIT_DIRTY}"

/* Full version string */
#define REFLECTOR_VERSION_STRING "${VERSION}${GIT_DIRTY}"

/* Git metadata */
#define REFLECTOR_GIT_HASH "${GIT_HASH}"
#define REFLECTOR_GIT_DATE "${GIT_DATE}"

/* Build information */
#define REFLECTOR_BUILD_DATE __DATE__
#define REFLECTOR_BUILD_TIME __TIME__

/* Helper macro to create version integer */
#define REFLECTOR_VERSION_CODE(major, minor, patch) \
    (((major) << 16) | ((minor) << 8) | (patch))

/* Current version as integer for comparisons */
#define REFLECTOR_VERSION_NUMBER \
    REFLECTOR_VERSION_CODE(REFLECTOR_VERSION_MAJOR, \
                          REFLECTOR_VERSION_MINOR, \
                          REFLECTOR_VERSION_PATCH)

#endif /* ${HEADER_GUARD} */
HEADER

echo "Generated version: ${VERSION}${GIT_DIRTY} (${GIT_HASH})"
